name: build
run-name: Build TS webpack bundle
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i
      - run: npm run build
      - uses: actions/upload-artifact@main
        with:
          name: page
          path: dist
          if-no-files-found: error
  # TODO: Remove bundle.js from src/ folder and add workflow/pipelines to generate artifacts and deploy to pages